language: generic
sudo: false

install:
  # conda
  - wget -c --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /tmp
  - bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y tensorflow scikit-learn pytest networkx matplotlib

script:
  - python setup.py install --user
  - pytest test/ -s
