language: generic
sudo: false

install:
  # conda
  - wget -c --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /tmp
  - bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y tensorflow scikit-learn pytest networkx matplotlib sphinx numpydoc

script:
  - python setup.py install --user
  - make html -C doc
  - pytest test/ -s

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone https://${GH_TOKEN}github.com/anthony-nouy/anthony-nouy.github.io.git
  - mkdir -p anthony-nouy.github.io/sphinx/${REPO_NAME}/${TRAVIS_BRANCH}
  - cp -r doc/_build/html/* anthony-nouy.github.io/sphinx/${REPO_NAME}/${TRAVIS_BRANCH}
  - cd anthony-nouy.github.io
  #- touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build ${REPO_NAME} ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1
